builder_url = "https://willem.habitat.sh/v1"
depot_url = "https://willem.habitat.sh/v1/depot"
github_client_id = "e98d2a94787be9af9c00"
github_token_auth_url = "https://willem.habitat.sh/v1/authenticate"
