$script = <<SCRIPT

# Virtual Box provider's synced folder implementation does not
# work well with the habitat compile so we copy to a 
# "real" folder
Copy-Item /src /src2 -Recurse -Force

cd /src2/components/hab/win
$env:ORIGIN_KEY = "#{ENV['ORIGIN_KEY']}"
./win-build.ps1

# Now copy the built artifacts back
Copy-Item /src2/components/hab/win/results /src/components/hab/win -Recurse -Force
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.synced_folder File.expand_path("../../../../", __FILE__), "/src"
  config.vm.provision "shell", inline: $script
end
