#!/bin/sh
rc=0

{{pkgPathFor "core/curl"}}/bin/curl --head --fail --max-time 1 -s \
  http://{{sys.ip}}:{{cfg.http.listen_port}}/v1/status > /dev/null

case $? in
  0)
    rc=0 ;;
  *)
    rc=2 ;;
esac

exit $rc
