FROM scratch
ENV PATH {{path}}
ADD {{rootfs}} /

# if primary_user_id != 0, chown!
#
# We can do this because a primary_user_id of 0 (i.e., root) is
# "falsy".  There's no reason to do this if the primary user is root,
# because root already owns all of /hab (because that's how ADD always
# works)
#
# (Also, sorry for `-R` instead of `--recursive`; Busybox doesn't
# recognize the latter :'(
{{#if primary_user_id }}
RUN chown -R {{primary_user_id}}:{{primary_group_id}} /hab

# This environment variable disables certain checks around installing
# packages (important for upgrade scenarios!). It is a short-term fix;
# long-term, we should just check to see if the user can write to the
# various directories under /hab that it needs.
ENV HAB_NON_ROOT=1
{{/if}}

USER {{primary_user_id}}:{{primary_group_id}}

{{#each volumes}}
RUN mkdir -p {{this}}
VOLUME {{this}}
{{/each}}
EXPOSE 9631 {{exposes}}
ENTRYPOINT ["/init.sh"]
CMD ["start", "{{primary_svc_ident}}"]
