log_level = "info"

[http]
listen = "0.0.0.0"
port   = 9636

[github]
url            = "https://api.github.com"
web_url        = "https://github.com"
client_id      = ""
client_secret  = ""
app_id         = 5565
webhook_secret = ""

[depot]
builds_enabled          = true
non_core_builds_enabled = true
events_enabled          = false

[segment]
url       = "https://api.segment.io"
write_key = ""
