#!/bin/sh
mkdir -p /opt/bldr/srvc/nginx/var
path_to_bldr_web="/opt/bldr/pkgs/{{bldr.origin}}/{{bldr.name}}/{{bldr.version}}/{{bldr.release}}"

rm -rf /opt/bldr/srvc/bldr-web/static* && cp -r $path_to_bldr_web/dist /opt/bldr/srvc/bldr-web/static
