#!/bin/bash
#
path_to_nginx=`cat /opt/bldr/pkgs/{{bldr.derivation}}/{{bldr.name}}/{{bldr.version}}/{{bldr.release}}/DEPS | grep nginx`
exec 2>&1
exec /opt/bldr/pkgs/$path_to_nginx/sbin/nginx -c /opt/bldr/srvc/bldr-web/config/nginx.conf
