postgres: hab svc start core/builder-datastore
api: /src/target/debug/bldr-api start --config /hab/svc/builder-api/user.toml
admin: /src/target/debug/bldr-admin start
router: /src/target/debug/bldr-router start
jobsrv: /src/target/debug/bldr-jobsrv start --config /hab/svc/builder-jobsrv/user.toml
sessionsrv: /src/target/debug/bldr-sessionsrv start --config /hab/svc/builder-sessionsrv/user.toml
originsrv: /src/target/debug/bldr-originsrv start --config /hab/svc/builder-originsrv/user.toml
worker: /src/target/debug/bldr-worker start --config /hab/svc/builder-worker/user.toml
