postgres: hab svc start core/builder-datastore
api: /src/target/debug/bldr-api start --config /hab/svc/builder-api/config.toml
admin: /src/target/debug/bldr-admin start
router: /src/target/debug/bldr-router start
jobsrv: /src/target/debug/bldr-jobsrv start --config /hab/svc/builder-jobsrv/config.toml
sessionsrv: /src/target/debug/bldr-sessionsrv start --config /hab/svc/builder-sessionsrv/config.toml
originsrv: /src/target/debug/bldr-originsrv start --config /hab/svc/builder-originsrv/config.toml
worker: /src/target/debug/bldr-worker start --config /hab/svc/builder-worker/config.toml
