#!/bin/bash

# This script is a wrapper around running a server and its migrations. It's
# necessary because forego doesn't let you run multiple commands.

set -e

if [ "$#" -lt "1" ] || [ "$#" -gt "2" ]; then
  echo "Usage: run-server <SERVER> [CONFIG_PATH]"
  echo "ex: run-server jobsrv /tmp/jobsrv.toml"
  exit 1
fi

# base_dir is the root of the habitat project, which eliminates the need
# to hardcode absolute paths.
base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

migrate="$base_dir/target/debug/bldr-$1 migrate"
start="$base_dir/target/debug/bldr-$1 start"

if [ "$#" -eq "2" ]; then
  migrate+=" --config $2"
  start+=" --config $2"
fi

if [ -z "$BLDR_NO_MIGRATIONS" ]; then
  eval $migrate
fi

eval $start
