#!/bin/sh
export RAILS_SAMPLE_HOME="{{pkg.path}}"
export RAILS_SAMPLE_DATA="{{pkg.svc_data_path}}"

echo "Removing previous version deployed at ${RAILS_SAMPLE_DATA}"
rm -rf ${RAILS_SAMPLE_DATA}/*

echo "Deploying new version from ${RAILS_SAMPLE_HOME} to ${RAILS_SAMPLE_DATA}"
cp -a ${RAILS_SAMPLE_HOME}/dist ${RAILS_SAMPLE_DATA}/dist

echo "Linking database.yml"
ln -sf {{pkg.svc_config_path}}/database.yml ${RAILS_SAMPLE_DATA}/dist/config/database.yml

export GEM_HOME="${RAILS_SAMPLE_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab-bpm pkgpath core/ruby)/lib/ruby/gems/2.3.0:$(hab-bpm pkgpath core/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(hab-bpm pkgpath core/gcc-libs)/lib"
export PATH="$PATH:${RAILS_SAMPLE_DATA}/dist/bin"
export RAILS_ENV="production"

chown -R hab:hab ${RAILS_SAMPLE_DATA}/dist
cd ${RAILS_SAMPLE_DATA}/dist

exec 2>&1

if [[ ! -f ${RAILS_SAMPLE_DATA}/.migrations_complete ]]; then
  echo "Running 'rake bootstrap' in ${PWD}"
  exec chpst -u hab bin/rake bootstrap && touch $RAILS_SAMPLE_DATA/.migrations_complete
fi
