#!/bin/sh
export RAILS_SAMPLE_DATA="{{pkg.svc_path}}/data"
export GEM_HOME="${RAILS_SAMPLE_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(bpm pkgpath chef/ruby)/lib/ruby/gems/2.3.0:$(bpm pkgpath chef/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(bpm pkgpath chef/gcc-libs)/lib"
export PATH="$PATH:${RAILS_SAMPLE_DATA}/dist/bin"
export RAILS_ENV="production"

cd $RAILS_SAMPLE_DATA/dist

exec 2>&1
exec chpst -u bldr ./bin/rails server -b {{cfg.rails_binding_ip}} -p {{cfg.rails_port}}
