rails_binding_ip = "0.0.0.0"
rails_port = 3000

database_name = "ruby-rails-sample_production"
database_username = "ruby-rails-sample"

# It's up to the end user to set a password for their database, we
# don't want to assume a default that can lead to insecure database
# servers running in the wild.
database_password = ""

# Normally you should use named service binding to bind the "database"
# name to the database service group, and this app will connect to the
# leader of that service group. If you do not use binding, this app
# will fall back to using the database host specified here (localhost).
# We recommend that this only be used for testing purposes.
database_host = "localhost"

# It's highly unlikely anyone would want to change this from the
# default, right? but it's configurable. Just in case.
database_port = 5432
