services:
  shell:
    platform: linux/amd64
    image: habitat/devshell
    build: ./
    privileged: true
    volumes:
      - .:/src
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - cache_artifacts
      - cache_keys
      - cargo
      - etc

  cache_artifacts:
    platform: linux/amd64
    image: tianon/true
    command: /true
    volumes:
      - /hab/cache/artifacts

  cache_keys:
    platform: linux/amd64
    image: tianon/true
    command: /true
    volumes:
      - /hab/cache/keys

  cargo:
    platform: linux/amd64
    image: tianon/true
    command: /true
    volumes:
      - /cargo-cache

  etc:
    platform: linux/amd64
    image: tianon/true
    command: /true
    volumes:
      - /hab/etc
