#########################
## Sass Lint File
#########################
# Linter Options
# Rule Configuration
rules:
  clean-import-paths: 0
  empty-line-between-blocks: false
  force-element-nesting: 0
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations: false
  nesting-depth: 0
  no-misspelled-properties:
    - 1
    - extra-properties:
      - osx-font-smoothing
  no-qualifying-elements: 0
  no-vendor-prefixes:
    - 2
    - excluded-identifiers:
      - webkit
      - moz
  placeholder-in-extend: 0
  property-sort-order: 0
  quotes:
    - 2
    - style: single
  shorthand-values: false
  single-line-per-selector: false
