pkg_name=linux-pam
pkg_origin=core
pkg_version=1.2.1
pkg_license=('MIT', 'GPL')
pkg_maintainer="The Habitat Contributors <humans@habitat.sh>"
pkg_source=http://www.linux-pam.org/library/Linux-PAM-1.2.1.tar.gz
pkg_filename=${pkg_name}-${pkg_version}.tar.gz
pkg_dirname=Linux-PAM-${pkg_version}
pkg_shasum=8e3f07fdbad5b1c030498fd6298e115e6f740d39d930390fc6937d14fa5c1b4a
pkg_deps=(core/glibc)
pkg_build_deps=(core/coreutils core/gcc core/make)
pkg_bin_dirs=(sbin)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
