#!/bin/sh

pkg_svc_run="nginx -c {{pkg.svc_config_path}}/nginx.conf"

if [ "\$(whoami)" = "root" ]; then
  exec chpst \
    -U {{pkg.svc_user}}:{{pkg.svc_group}} \
    -u {{pkg.svc_user}}:{{pkg.svc_group}} \
    ${pkg_svc_run} 2>&1
else
  exec ${pkg_svc_run} 2>&1
fi
