[package]
name = "habitat-eventsrv"
version = "0.0.0"
authors = [
  "Josh Black <raskchanky@gmail.com>",
  "Christopher Maier <cmaier@chef.io>",
  "Jamie Winsor <reset@habitat.sh>",
]
description = "Habitat EventSrv service"
build = "build.rs"
workspace = "../../"

[dependencies]
clippy = {version = "*", optional = true}
byteorder = "*"
clap = { version = "*", features = [ "suggestions", "color", "unstable" ] }
env_logger = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
habitat-eventsrv-protocol = { path = "../eventsrv-protocol" }
log = "*"
protobuf = "1.5.1"
serde = "*"
serde_derive = "*"
time = "*"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[build-dependencies]
pkg-config = "*"

[features]
default = []
protocols = []

[[bin]]
name = "eventsrv"
path = "src/main.rs"

# this is used for testing
[[bin]]
name = "subscriber"
path = "src/subscriber.rs"
