#!/bin/sh
export RADIANT_HOME="{{pkg.path}}"
export RADIANT_DATA="{{pkg.svc_path}}/data"

echo "Removing previous version deployed at ${RADIANT_DATA}"
rm -rf ${RADIANT_DATA}*

echo "Deploying new version from ${RADIANT_HOME} to ${RADIANT_DATA}"
cp -a ${RADIANT_HOME}/dist ${RADIANT_DATA}

# echo "Linking radiant.conf"
# ln -s {{pkg.svc_path}}/config/radiant.conf ${RADIANT_DATA}/dist/config/radiant.conf

export GEM_HOME="${RADIANT_DATA}/dist/vendor/bundle"
export GEM_PATH="$(bpm pkgpath chef/bundler)"
export LD_LIBRARY_PATH="$(bpm pkgpath chef/gcc-libs)/lib"
export PATH="$PATH:${RADIANT_DATA}/dist/bin"
export RAILS_ENV="production"

# mkdir -p ${RADIANT_DATA}/dist/log
# touch ${RADIANT_DATA}/dist/log/production.log

chown -R bldr:bldr ${RADIANT_DATA}/dist
cd ${RADIANT_DATA}/dist

exec 2>&1

if [[ ! -f ${RADIANT_DATA}/.migrations_complete ]]; then
  echo "Running 'rake db:create db:migrate' in ${PWD}"
  exec chpst -u bldr bin/rake db:create db:migrate && touch $RADIANT_DATA/.migrations_complete
fi
