#!/bin/sh
set -x

rc=0

{{pkgPathFor "core/curl"}}/bin/curl --head --fail --max-time 1 \
  http://{{sys.ip}}:{{cfg.http.listen_port}}/health > /dev/null

case $? in
  0)
    rc=0 ;;
  *)
    rc=2 ;;
esac

exit $rc
