#!/bin/sh

set -x

# default return code is 0
rc=0

{{pkgPathFor "core/curl"}}/bin/curl --head --fail --max-time 1 \
  http://{{sys.ip}}:{{cfg.http.listen_port}}/health

case $? in
  # Zero exit status means curl got back a 200 end everything is ok.
  0)
    rc=0 ;;
  # Anything else is critical
  *)
    rc=2 ;;
esac

exit $rc
