#!/opt/bldr/pkgs/chef/busybox/1.23.2/20151116135232/bin/sh
cd /opt/bldr/srvc/simple_service

if [ "$(whoami)" = "root" ]; then
  exec /opt/bldr/pkgs/chef/busybox/1.23.2/20151116135232/bin/chpst \
    -U bldr:bldr \
    -u bldr:bldr \
    /opt/bldr/pkgs/test/simple_service/0.0.1/20151116161429/bin/simple_service 2>&1
else
  exec /opt/bldr/pkgs/test/simple_service/0.0.1/20151116161429/bin/simple_service 2>&1
fi
