FROM microsoft/windowsservercore:ltsc2016
ADD {{rootfs}} /

EXPOSE 9631 {{exposes}}
RUN SET HAB_FEAT_OFFLINE_INSTALL=ON && \
    {{~ #if environment}}
    {{~ #each environment}}
        SET {{@key}}={{{this}}} && \
    {{~ /each}}
    {{~ /if}}
    {{hab_path}} pkg install {{installed_primary_svc_ident}}
ENTRYPOINT ["{{hab_path}}", "sup", "run", "{{primary_svc_ident}}"]
