FROM microsoft/windowsservercore
ADD {{rootfs}} /

EXPOSE 9631 {{exposes}}
{{~ #if install_hook_feat}}
    RUN SET HAB_FEAT_OFFLINE_INSTALL=ON && \
        SET HAB_FEAT_INSTALL_HOOK=ON && \
        {{~ #if environment}}
        {{~ #each environment}}
            SET {{@key}}={{{this}}} && \
        {{~ /each}}
        {{~ /if}}
        {{hab_path}} pkg install {{installed_primary_svc_ident}}
{{~ /if}}
ENTRYPOINT ["{{hab_path}}", "sup", "run", "{{primary_svc_ident}}"]
