FROM scratch
ENV PATH {{path}}
ADD {{rootfs}} /

EXPOSE 9631 {{exposes}}
RUN HAB_FEAT_OFFLINE_INSTALL=ON \
    {{~ #if environment}}
    {{~ #each environment}}
        {{@key}}={{{this}}} \
    {{~ /each}}
    {{~ /if}}
    {{hab_path}} pkg install {{installed_primary_svc_ident}}
ENTRYPOINT ["/init.sh"]
CMD ["run", "{{primary_svc_ident}}"]
