#!/bin/sh

sv status /opt/bldr/svc/hana
rc=0
/usr/sap/hostctrl/exe/sapcontrol -nr {{instance-id}} -function GetProcessList
case $? in
  0)
    rc=1 ;;
  3)
    rc=0 ;;
  4)
    rc=2 ;;
  *)
    rc=3 ;;
esac

echo
cat /opt/bldr/svc/hana/config.toml

exit $rc

