#!/bin/bash

trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   # remove trailing whitespace characters
    echo "$var"
}

latest_package() {
  # Count the number of slashes, and use it to make a choice
  # about what to return as the latest package.
  latest_package_flags=$(echo $1 | grep -o '/' | wc -l)
  case $(trim $latest_package_flags) in
    "3")
      echo "/opt/bldr/pkgs/$1" ;;
    "2")
      echo $(find /opt/bldr/pkgs/${1} -maxdepth 1 -type d | sort -r | head -n 1) ;;
    "1")
      echo $(find /opt/bldr/pkgs/${1} -maxdepth 2 -type d | sort -r | head -n 1) ;;
  esac
}

hana_path=$(latest_package sap/hana)

# Because we like to party, we just put all the libraries in the lib cache.
find /opt/bldr/pkgs -name 'LD_RUN_PATH' | xargs cat | tr ':' '\n' > /etc/ld.so.conf
glibc_path=$(latest_package chef/glibc)
$glibc_path/sbin/ldconfig.real

export LD_LIBRARY_PATH=$(find /opt/bldr/pkgs -name 'LD_RUN_PATH' | xargs cat | tr '\n' :)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$hana_path/bin/instruntime
pkg_prefix=$hana_path
# This needs to have the path be correct for hana

if [[ -d "/usr/sap" ]]; then
  echo "HANA is already installed"
else
  {{#census.me.leader}}
  echo "Installing HANA runtime"
  echo "return 0" > /bin/chkconfig
  chmod a+x /bin/chkconfig
  cat <<EOT > /tmp/hana-passwords
<?xml version="1.0" encoding="UTF-8"?>
<Passwords>
<password>{{password}}</password>
<sapadm_password>{{sapadm-password}}</sapadm_password>
<system_user_password>{{system-user-password}}</system_user_password>
<root_password>{{root-password}}</root_password>
</Passwords>
EOT
  env HDB_IGNORE_HANA_PLATFORM_CHECK=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
  cat /tmp/hana-passwords | $pkg_prefix/bin/hdblcm \
    --b \
    --components=all \
    --sid {{sid}} \
    --number={{instance-id}} \
    --userid=5150 \
    --groupid=5150 \
    --shell=/bin/bash \
    --batch \
    --read_password_from_stdin=xml \
    --hdbinst_server_ignore=check_min_mem,check_platform,check_diskspace \
    --ignore=check_signature_file
  {{/census.me.leader}}
  {{#census.me.follower}}
  $pkg_prefix/bin/hdblcm --action=install --addhosts={{census.me.hostname}}:role={{role}}
  {{/census.me.follower}}
fi
