# NGINX Tunables

#
# For help with NGINX Config Tuning, refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html
#

# worker_processes: Number of NGINX processes. Default = 1
worker_processes = 4

# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024

# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60
