habitatConfig({
    habitat_api_url: "{{cfg.app_url}}",
    community_url: "{{cfg.community_url}}",
    docs_url: "{{cfg.docs_url}}",
    environment: "{{cfg.environment}}",
    friends_only: {{cfg.friends_only}},
    github_client_id: "{{cfg.github.client_id}}",
    github_api_url: "{{cfg.github.url}}",
    github_web_url: "{{cfg.github.web_url}}",
    github_app_url: "{{cfg.github.app_url}}",
    github_app_id: "{{cfg.github.app_id}}",
    source_code_url: "{{cfg.source_code_url}}",
    tutorials_url: "{{cfg.tutorials_url}}",
    version: "{{pkg.ident}}",
    www_url: "{{cfg.www_url}}",
    status_url: "{{cfg.status_url}}",
    forums_url: "{{cfg.forums_url}}",
    events_url: "{{cfg.events_url}}",
    roadmap_url: "{{cfg.roadmap_url}}",
    feature_requests_url: "{{cfg.feature_requests_url}}",
    slack_url: "{{cfg.slack_url}}",
    youtube_url: "{{cfg.youtube_url}}",
    demo_app_url: "{{cfg.demo_app_url}}"
});
