# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :x64_mingw]

# For better code snippets in markdown
gem 'redcarpet'
gem 'middleman-vegas'

# Middleman Gems
gem 'middleman', '>= 4.1'
gem 'middleman-autoprefixer'
gem 'middleman-livereload'
gem 'middleman-s3_sync'
gem 'middleman-sprockets'
gem 'middleman-blog', '>= 4.0'
gem 'middleman-minify-html'
gem 'mime-types'


gem 'rubocop', require: false
gem 'scss_lint', require: false
gem 'checker', require: false

group :development do
  gem 'pry'
end
