# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :x64_mingw]

# For better code snippets in markdown
gem 'redcarpet'
gem 'middleman-vegas'

# Middleman Gems
gem 'middleman', '>= 4.1.2'
gem 'middleman-s3_sync'
gem 'middleman-sprockets', "~> 4.0.0.rc"
gem "middleman-compass"
gem 'middleman-blog', '>= 4.0'
gem 'middleman-minify-html'
gem 'mime-types'

# Vendor prefixes for sass
gem 'middleman-autoprefixer'

# Live-reloading plugin
gem "middleman-livereload", "~> 3.4"

gem 'rubocop', require: false
gem 'scss_lint', require: false
gem 'checker', require: false

group :development do
  gem 'pry'
end
