# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-8.2"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../plans", "/src"

  config.vm.provision "shell", inline: <<-SHELL
set -eu

export http_proxy=#{ENV["http_proxy"]}
export https_proxy=#{ENV["https_proxy"]}
export BLDR_REPO=#{ENV["BLDR_REPO"]}
export STUDIO_TYPE=#{ENV["STUDIO_TYPE"]}
export STUDIO_TYPE=${STUDIO_TYPE:=bldr}

if ! command -v studio > /dev/null; then
#{IO.read("studio-install.sh")}
fi

mkdir -p /src
cd /src
studio -t $STUDIO_TYPE new

cat <<-EOF > /home/vagrant/.bash_profile
if [ -n "\\${PS1}" -o "\\$-" = "*i*" ]; then
  cd /src
  exec sudo env \
    http_proxy=${http_proxy:-} \
    https_proxy=${https_proxy:-} \
    BLDR_REPO=${BLDR_REPO:-} \
    studio enter
fi
EOF
  SHELL
end
