#!/bin/bash

echo "$(date): Executing Post Run Hook with templated value: {{cfg.post_run_templated_value}}"
EXIT_CODE='{{#if cfg.post_run_exit_code}}{{cfg.post_run_exit_code}}{{else}}0{{/if}}'
exit "$EXIT_CODE"