worker_rlimit_nofile = 8192
worker_processes = "auto"

[events]
worker_connections = 8000

[http]
listen_port = 8081
sendfile = "on"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = "20s"

# This disables the SSL redirect in the nginx.conf configuration.
# DO NOT DISABLE THIS IN PRODUCTION ENVIRONMENTS!
enable_ssl = true
