#!/opt/bldr/pkgs/bldr/busybox/1.23.2/20150904202315/bin/sh
cd /opt/bldr/srvc/simple_service

if [ "$(whoami)" = "root" ]; then
  exec /opt/bldr/pkgs/bldr/busybox/1.23.2/20150904202315/bin/chpst \
    -U bldr:bldr \
    -u bldr:bldr \
    /opt/bldr/pkgs/bldr/simple_service/0.0.1/20150905163048/bin/simple_service 2>&1
else
  exec /opt/bldr/pkgs/bldr/simple_service/0.0.1/20150905163048/bin/simple_service 2>&1
fi
