#!/usr/bin/env expect

set env(HAB_NOCOLORING) true
set studio_command $::env(STUDIO_COMMAND)
set studio_test [lindex $argv 0]
# Print out some helpful tracing messages in the test output.

proc log {message} {
    puts "LOG >>> $message"
}

# Cleanup after the test
exit -onexit {
    exec $studio_command rm
}

# Installing packages can take time
set timeout 30

# {*} Syntax explanation:
# https://www.tcl.tk/man/tcl/TclCmd/Tcl.htm [5] Argument Expansion
spawn {*}$studio_command enter
expect {
  {\[default:/src:0]#} { 
    log "Studio entered successfully"
  }
  eof {
    error "Unable to enter studio"
  }
  timeout {
    error "Timeout entering studio"
  } 
}

send "$studio_test\n"
expect {
  {\[PASS]} { }
  {\[FAIL]} { error "Studio internals tests failed" }
  timeout { error "Studio internals tests timed out" }
}
