pkg_name=libsodium
pkg_distname=$pkg_name
pkg_origin=chef
pkg_version=1.0.8
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=('libsodium')
pkg_source=https://download.libsodium.org/libsodium/releases/${pkg_name}-${pkg_version}.tar.gz
pkg_shasum=c0f191d2527852641e0a996b7b106d2e04cbc76ea50731b2d0babd3409301926
pkg_dirname=${pkg_distname}-${pkg_version}
pkg_deps=(chef/glibc)
pkg_build_deps=(chef/autoconf chef/automake chef/diffutils chef/patch chef/make chef/gcc chef/sed)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
