FROM scratch
MAINTAINER Adam Jacob <adam@chef.io>
ENV PATH /bin:/sbin:/opt/bldr/pkgs/bldr/bldr/0.0.1/20150525020827/bin:/opt/bldr/pkgs/bldr/gnupg/1.4.19/20150525020658/bin:/opt/bldr/pkgs/bldr/busybox/1.23.2/20150525020612/bin:/opt/bldr/pkgs/bldr/busybox/1.23.2/20150525020612/sbin
WORKDIR /
ADD bldr-base.tar.bz2 .
CMD ['sh']
