[app]
{{toToml cfg.app}}
routers = [
  {{~#eachAlive bind.router.members as |member|}}
  { host = "{{member.sys.ip}}", port = {{member.cfg.port}} },
  {{~/eachAlive}}
]

[permissions]
{{toToml cfg.permissions}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}
