[package]
name = "habitat_api_client"
version = "0.0.0"
authors = ["Josh Black <jblack@chef.io>"]
workspace = "../"

[dependencies]
clippy = {version = "*", optional = true}
hyper = "0.10"
hyper-openssl = ""
log = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
url = "*"

[dependencies.habitat_core]
path = "../../habitat/core"

[dependencies.habitat_http_client]
path = "../http-client"
