#!/bin/sh

EXIT_NOW=0

set_exit_now() {
  EXIT_NOW=1
}

trap "set_exit_now" INT TERM HUP
echo "-- Starting App --"
echo ""
cat {{pkg.svc_config_path}}/app.conf
echo ""
echo "-- Running on {{svc.me.sys.ip}} --"

while [ 1 ]; do
  if [ $EXIT_NOW = 1 ]; then
     echo "-- Shutting Down --"
     exit 0
  fi
  sleep 1
done
