# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.10"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y wget curl git

    # You'll need this for running most services
    adduser hab

    # You'll want this if you want to build a plan
    git clone https://github.com/habitat-sh/core-plans.git

    # You'll also want the keys for building for whatever origin you
    # choose.
    #
    # It expects you to have HAB_ORIGIN and HAB_AUTH_TOKEN set in your
    # environment when you provision the VM.
    #
    # Additionally, it will install from the *staging* channel unless
    # you specifically override this with the INSTALL_CHANNEL environment
    # variable. This is the default because this VM is mostly used for
    # manual evaluation of release candidates from that channel.
    curl https://raw.githubusercontent.com/habitat-sh/habitat/main/components/hab/install.sh -o install.sh
    bash install.sh -t x86_64-linux-kernel2 -c #{ENV.fetch('INSTALL_CHANNEL', 'staging')}
    sudo hab license accept
    sudo -u vagrant hab origin key download #{ENV['HAB_ORIGIN']} --secret --auth=#{ENV['HAB_AUTH_TOKEN']}
  SHELL
end
