# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw]

# Middleman Gems
gem 'middleman-sprockets', '>= 4.0.0.rc.1'
gem 'middleman', '>= 4.0.0.rc.1'
gem 'middleman-livereload'
gem 'middleman-autoprefixer'

gem 'rubocop', require: false
gem 'scss_lint', require: false
gem 'checker', require: false

group :development do
  gem 'pry'
end
