#!/bin/sh
set -e

PGPASSWORD={{cfg.datastore.password}}

if [ $(psql -l -U hab -h {{bind.datastore.first.sys.ip}} | grep {{cfg.datastore.database}} | wc -l) -eq 0 ]; then
  createdb -h {{bind.datastore.first.sys.ip}} -p {{bind.datastore.first.cfg.port}} -U hab {{cfg.datastore.database}}
fi
