# The URL for the builder service
builder_url = ""

# The URL for community information
community_url = "https://www.habitat.sh/community"

# The URL for the depot service
depot_url = ""

# The URL for documentation
docs_url = "https://docs.habitat.sh"

# The environment in which we're running. If "production", enable
# production mode
environment = "production"

# The URL for Habitat's source code
# GitHub Client ID for OAuth2
github_client_id = ""

# The URL used to get a GitHub token
github_token_auth_url = ""

# The URL for the Habitat source code
source_code_url = "https://github.com/habitat-sh/habitat"

# The URL for tutorials
tutorials_url = "https://www.habitat.sh/tutorials"
