# The URL for the Habitat API service (including the API version)
habitat_api_url = ""

# The URL for community information
community_url = "https://www.habitat.sh/community"

# The URL for documentation
docs_url = "https://www.habitat.sh/docs"

# The environment in which we're running. If "production", enable
# production mode
environment = "production"

# The URL for Habitat's source code
# GitHub Client ID for OAuth2
github_client_id = ""

# The URL for the Habitat source code
source_code_url = "https://github.com/habitat-sh/habitat"

# The URL for tutorials
tutorials_url = "https://www.habitat.sh/tutorials"

# The main website URL
www_url = "https://www.habitat.sh"