#!/usr/bin/env pwsh

Write-Output "install hook {{pkg.name}}"

$result = Test-Path "{{pkgPathFor "habitat-testing/dep-pkg-2"}}/INSTALL_HOOK_STATUS" -ErrorAction SilentlyContinue

if(!$result) {
    exit 1
}
