auto_publish = {{cfg.auto_publish}}
data_path = "{{pkg.svc_data_path}}"
key_dir = "{{pkg.svc_files_path}}"
log_path = "{{pkg.svc_path}}/logs"
bldr_channel = "{{cfg.bldr_channel}}"
features_enabled = "{{cfg.features_enabled}}"
{{~#eachAlive bind.depot.members as |member|}}
{{~#if @first}}
bldr_url = "{{member.cfg.url}}"
{{~/if}}
{{~/eachAlive}}
airlock_enabled = {{cfg.airlock_enabled}}
{{~#if cfg.network_interface}}
network_interface = "{{cfg.network_interface}}"
{{~/if}}
{{~#if cfg.network_gateway}}
network_gateway = "{{cfg.network_gateway}}"
{{~/if}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.worker_port}}
heartbeat = {{member.cfg.worker_heartbeat}}
log_port = {{member.cfg.log_port}}
{{~/eachAlive}}
